#!/bin/bash
#SBATCH -p mlhiwidlc_gpu-rtx2080-advanced # partition (queue)
#SBATCH -t 23:59:59 # time (D-HH:MM:SS)
#SBATCH --gres=gpu:8
#SBATCH -D /work/dlclarge1/rapanti-stn_cifar/dino_cifar10
#SBATCH -J dino-vit_nano-cifar10-baseline-ep300-crops2
#SBATCH -o /work/dlclarge1/rapanti-stn_cifar/experiments/dino-vit_nano-cifar10-baseline-ep300-crops2/log/%x.%A.%a.%N.out
#SBATCH -e /work/dlclarge1/rapanti-stn_cifar/experiments/dino-vit_nano-cifar10-baseline-ep300-crops2/log/%x.%A.%a.%N.out
#SBATCH --mail-type=ALL # (receive mails about end and timeouts/crashes of your job)
#SBATCH --array 0-25%1

# Print some information about the job to STDOUT
echo "Workingdir: $PWD"
echo "Started at $(date)"
echo "Running job $SLURM_JOB_NAME with given JID $SLURM_JOB_ID on queue $SLURM_JOB_PARTITION"

source /home/rapanti/.profile
source activate dino

EXP_D=/work/dlclarge1/rapanti-stn_cifar/experiments/
# Job to perform
torchrun \
  --standalone \
  --nproc_per_node=8 \
  --nnodes=1 \
  main_dino.py \
    --arch vit_nano \
    --img_size 32 \
    --patch_size 4 \
    --data_path /work/dlclarge1/rapanti-stn_cifar/data/datasets/CIFAR10 \
    --dataset CIFAR10 \
    --output_dir $EXP_D"dino-vit_nano-cifar10-baseline-ep300-crops2" \
    --epochs 300 \
    --warmup_epochs 10 \
    --batch_size_per_gpu 512 \
    --use_fp16 true \
    --local_crops_number 2 \
    --num_workers 8

torchrun \
  --standalone \
  --nproc_per_node=8 \
  --nnodes=1 \
  eval_linear.py \
    --arch vit_nano \
    --dataset CIFAR10 \
    --data_path /work/dlclarge1/rapanti-stn_cifar/data/datasets/CIFAR10 \
    --pretrained_weights /work/dlclarge1/rapanti-stn_cifar/experiments/dino-vit_nano-cifar10-baseline-ep300-crops2/checkpoint.pth \
    --img_size 32 \
    --patch_size 4 \
    --output_dir $EXP_D"eval_linear-vit_nano-cifar10-baseline-ep300-crops2" \
    --epochs 100 \
    --batch_size_per_gpu 768 \
    --lr 0.01 \
    --weight_decay 0.0001 \
    --num_workers 8 \
    --val_freq 10

# Print some Information about the end-time to STDOUT
echo "DONE"
echo "Finished at $(date)"
scancel $SLURM_ARRAY_JOB_ID
